Commands:
  Base:
    Command: "vote"
    Aliases:
      - "voting"
      - "phantomvote"
  Admin:
    Command: "voteadmin"
    Aliases:
      - "votingadmin"
      - "phantomvoteadmin"

# Voting Configuration for Rewards
Sound:
  enabled: true
  soundType: "ENTITY_PLAYER_LEVELUP"
Rewards:
  # These are the rewards that are given to the player when they vote, regardless of the vote site.
  Default:
    Commands:
      - "give %player% minecraft:diamond 1"
      - "eco give %player% 500"

  # Vote Rewards
  VoteRewards:
    "Common":
      Chance: 100                 # Percentage chance for this reward (100 = guaranteed)
      Commands:                   # List of commands to run if this reward is selected
        - "give %player% minecraft:gold_ingot 3"
      Random: false               # If true, randomly chooses one command

    "Rare":
      Chance: 10                  # 10% chance to receive this rare reward
      Permission: "phantomvote.rewards.rare" # Permission required to receive this reward
      Commands:
        - "give %player% minecraft:diamond_block 1"
        - "eco give %player% 2000"
      Random: false